on:
  push:
    branches: [ master ]
  pull_request:
name: Build
jobs:
  flatpak:
    name: "build-extension"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v5
      with:
        bundle: org.freedesktop.Platform.VulkanLayer.LatencyFleX.flatpak
        manifest-path: org.freedesktop.Platform.VulkanLayer.LatencyFleX.yml
        cache-key: flatpak-builder-${{ github.sha }}
